/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package irms.ui.panel;

import irms.db.MySQLConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class categoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form categoryPanel
     */
    public categoryPanel() {
        initComponents();
        lblBackground.setIcon(new javax.swing.ImageIcon(
            getClass().getResource("/irms/resources/background/Category List.png")
        ));
        txtSearch.setEditable(true);
        loadCategories();
        autoSearchCategory();
        styleTable();
    }
    
    public void loadCategories() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        String sql = "SELECT category_id, category_name " +
                     "FROM categories " +
                     "ORDER BY category_id";

        try (Connection conn = MySQLConnect.getConnection();
             PreparedStatement pst = conn.prepareStatement(sql);
             ResultSet rs = pst.executeQuery()) {

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("category_id"),
                    rs.getString("category_name")
                });
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Load error: " + e.getMessage());
        }
    }
    
    public void searchCategories(String keyword) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        String sql = "SELECT category_id, category_name " +
                     "FROM categories " +
                     "WHERE category_name LIKE ? OR CAST(category_id AS CHAR) LIKE ? " +
                     "ORDER BY category_id";

        try (Connection conn = MySQLConnect.getConnection();
             PreparedStatement pst = conn.prepareStatement(sql)) {

            String like = "%" + keyword + "%";
            pst.setString(1, like);
            pst.setString(2, like);

            try (ResultSet rs = pst.executeQuery()) {
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt("category_id"),
                        rs.getString("category_name")
                    });
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Search error: " + e.getMessage());
        }
    }
    
       public void autoSearchCategory() {
        txtSearch.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                searchNow();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                searchNow();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                searchNow();
            }

            private void searchNow() {
                String keyword = txtSearch.getText().trim();

                if (keyword.isEmpty()) {
                    loadCategories();
                } else {
                    searchCategories(keyword);
                }
            }
        });
    }
    public void styleTable() {
    jTable1.setRowHeight(28);
    jTable1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
    jTable1.setGridColor(new java.awt.Color(180, 180, 180));
    jTable1.setSelectionBackground(new java.awt.Color(180, 200, 160));
    jTable1.setSelectionForeground(java.awt.Color.BLACK);
    jTable1.setRowSelectionAllowed(true);
    jTable1.setFocusable(false);

    javax.swing.table.JTableHeader header = jTable1.getTableHeader();
    header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
    header.setBackground(new java.awt.Color(220, 229, 236));
    header.setForeground(new java.awt.Color(54, 67, 20));
    header.setReorderingAllowed(false);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnDelete = new irms.ui.components.RoundedButtons();
        btnEdit = new irms.ui.components.RoundedButtons();
        btnAdd = new irms.ui.components.RoundedButtons();
        txtSearch = new javax.swing.JTextField();
        lblBackground = new javax.swing.JLabel();

        setBackground(new java.awt.Color(200, 212, 222));
        setPreferredSize(new java.awt.Dimension(1130, 768));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Search:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 60, 30));

        jTable1.setBackground(new java.awt.Color(247, 249, 251));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTable1.setForeground(new java.awt.Color(36, 48, 24));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Category"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(142, 160, 173));
        jTable1.setShowGrid(false);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 670, 510));

        btnDelete.setBackground(new java.awt.Color(72, 92, 13));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete Category");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 160, 50));

        btnEdit.setBackground(new java.awt.Color(154, 151, 33));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit Category");
        btnEdit.addActionListener(this::btnEditActionPerformed);
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 160, 50));

        btnAdd.setBackground(new java.awt.Color(72, 92, 13));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add Category");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 248, 160, 50));

        txtSearch.setEditable(false);
        txtSearch.setBackground(new java.awt.Color(247, 249, 251));
        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(26, 48, 24));
        txtSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 142, 88)));
        txtSearch.addActionListener(this::txtSearchActionPerformed);
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 380, 34));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irms/resources/background/Category List.png"))); // NOI18N
        add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a category to delete.");
            return;
        }

        int categoryId = (int) jTable1.getValueAt(row, 0);
        String categoryName = jTable1.getValueAt(row, 1).toString();

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Delete category: " + categoryName + "?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try (Connection conn = MySQLConnect.getConnection()) {

            String checkSql = "SELECT COUNT(*) FROM products WHERE category_id = ?";
            try (PreparedStatement pst = conn.prepareStatement(checkSql)) {
                pst.setInt(1, categoryId);

                try (ResultSet rs = pst.executeQuery()) {
                    if (rs.next() && rs.getInt(1) > 0) {
                        JOptionPane.showMessageDialog(
                            this,
                            "Cannot delete category.\nThere are products still using this category."
                        );
                        return;
                    }
                }
            }

            String deleteSql = "DELETE FROM categories WHERE category_id = ?";
            try (PreparedStatement pst = conn.prepareStatement(deleteSql)) {
                pst.setInt(1, categoryId);
                pst.executeUpdate();
            }

            JOptionPane.showMessageDialog(this, "Category deleted successfully!");
            loadCategories();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Delete error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a category to edit.");
            return;
        }

        int categoryId = (int) jTable1.getValueAt(selectedRow, 0);
        String oldName = jTable1.getValueAt(selectedRow, 1).toString();

        String newName = JOptionPane.showInputDialog(this, "Edit Category Name:", oldName);

        if (newName == null) return;

        newName = newName.trim();
        if (newName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Category name cannot be empty.");
            return;
        }

        String checkSql = "SELECT COUNT(*) FROM categories WHERE category_name = ? AND category_id <> ?";
        String updateSql = "UPDATE categories SET category_name = ? WHERE category_id = ?";

        try (Connection conn = MySQLConnect.getConnection()) {

            try (PreparedStatement checkPst = conn.prepareStatement(checkSql)) {
                checkPst.setString(1, newName);
                checkPst.setInt(2, categoryId);

                try (ResultSet rs = checkPst.executeQuery()) {
                    if (rs.next() && rs.getInt(1) > 0) {
                        JOptionPane.showMessageDialog(this, "Category name already exists!");
                        return;
                    }
                }
            }

            try (PreparedStatement pst = conn.prepareStatement(updateSql)) {
                pst.setString(1, newName);
                pst.setInt(2, categoryId);
                pst.executeUpdate();
            }

            JOptionPane.showMessageDialog(this, "Category updated successfully!");
            loadCategories();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Update error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String catName = JOptionPane.showInputDialog(this, "Enter Category Name:");

        if (catName == null) return;

        catName = catName.trim();
        if (catName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Category name cannot be empty.");
            return;
        }

        String checkSql = "SELECT COUNT(*) FROM categories WHERE category_name = ?";
        String insertSql = "INSERT INTO categories (category_name, description) VALUES (?, NULL)";

        try (Connection conn = MySQLConnect.getConnection()) {

            try (PreparedStatement checkPst = conn.prepareStatement(checkSql)) {
                checkPst.setString(1, catName);

                try (ResultSet rs = checkPst.executeQuery()) {
                    if (rs.next() && rs.getInt(1) > 0) {
                        JOptionPane.showMessageDialog(this, "Category already exists.");
                        return;
                    }
                }
            }

            try (PreparedStatement pst = conn.prepareStatement(insertSql)) {
                pst.setString(1, catName);
                pst.executeUpdate();
            }

            JOptionPane.showMessageDialog(this, "Category added successfully!");
            loadCategories();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Insert error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
