/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package irms;


import java.awt.Color;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;


/**
 *
 * @author USER
 */
public class brandPanel extends javax.swing.JPanel {

    /**
     * Creates new form testBrandPanel
     */
    public brandPanel() {
        initComponents();
        loadBrands();
        autoSearchBrands();
        styleTable();
        txtSearch.setEditable(true);
    }
    private void openPanel(javax.swing.JPanel panel) {
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (window instanceof MainFrame) {
            ((MainFrame) window).showPanel(panel);
        }
    }
    
    public void loadBrands() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        String sql = "SELECT * FROM brands ORDER BY brand_id";

        try (Connection conn = MySQLConnect.getConnection();
             PreparedStatement pst = conn.prepareStatement(sql);
             ResultSet rs = pst.executeQuery()) {

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("brand_id"),
                    rs.getString("brand_name")
                });
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void searchBrands(String keyword) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        String sql = "SELECT * FROM brands WHERE brand_name LIKE ? OR brand_id LIKE ?";

        try (Connection conn = MySQLConnect.getConnection();
             PreparedStatement pst = conn.prepareStatement(sql)) {

            pst.setString(1, "%" + keyword + "%");
            pst.setString(2, "%" + keyword + "%");

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("brand_id"),
                    rs.getString("brand_name")
                });
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void autoSearchBrands() {
        txtSearch.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) { searchNow(); }
            public void removeUpdate(DocumentEvent e) { searchNow(); }
            public void changedUpdate(DocumentEvent e) { searchNow(); }

            private void searchNow() {
                String text = txtSearch.getText().trim();
                if (text.isEmpty()) {
                    loadBrands();
                } else {
                    searchBrands(text);
                }
            }
        });
    }

    public void styleTable() {
        jTable1.setRowHeight(28);
        jTable1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        jTable1.setGridColor(new java.awt.Color(180, 180, 180));
        jTable1.setSelectionBackground(new java.awt.Color(180, 200, 160));
        jTable1.setSelectionForeground(java.awt.Color.BLACK);
        jTable1.setRowSelectionAllowed(true);
        jTable1.setFocusable(false);

        javax.swing.table.JTableHeader header = jTable1.getTableHeader();
        header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        header.setBackground(new java.awt.Color(220, 229, 236));
        header.setForeground(new java.awt.Color(54, 67, 20));
        header.setReorderingAllowed(false);
    }
    
    private void goToMainFrameHome() {
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (window instanceof MainFrame) {
            ((MainFrame) window).goHome();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(247, 249, 251));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTable1.setForeground(new java.awt.Color(36, 48, 24));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Brand"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(142, 160, 173));
        jTable1.setShowGrid(false);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 670, 510));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Search:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, 30));

        btnDelete.setText("Delete Brand");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, 120, 40));

        btnEdit.setText("Edit Brand");
        btnEdit.addActionListener(this::btnEditActionPerformed);
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 120, 40));

        btnAdd.setForeground(new java.awt.Color(36, 48, 24));
        btnAdd.setText("Add Brand");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 120, 38));

        txtSearch.setEditable(false);
        txtSearch.setBackground(new java.awt.Color(247, 249, 251));
        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(26, 48, 24));
        txtSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(126, 142, 88)));
        txtSearch.addActionListener(this::txtSearchActionPerformed);
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 380, 34));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a brand");
            return;
        }

        int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        String name = jTable1.getValueAt(row, 1).toString();

        int confirm = JOptionPane.showConfirmDialog(this,
            "Delete brand: " + name + "?",
            "Confirm",
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try (Connection conn = MySQLConnect.getConnection()) {
                String sql = "DELETE FROM brands WHERE brand_id=?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setInt(1, id);
                pst.executeUpdate();

                loadBrands();
                JOptionPane.showMessageDialog(this, "Deleted!");

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a brand");
            return;
        }

        int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        String current = jTable1.getValueAt(row, 1).toString();

        JTextField txt = new JTextField(current);

        JPanel panel = new JPanel(new GridLayout(0,1));
        panel.add(new JLabel("Brand Name:"));
        panel.add(txt);

        int result = JOptionPane.showConfirmDialog(this, panel, "Edit Brand", JOptionPane.OK_CANCEL_OPTION);

        if (result == JOptionPane.OK_OPTION) {
            String newName = txt.getText().trim();

            if (newName.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Empty field!");
                return;
            }

            try (Connection conn = MySQLConnect.getConnection()) {
                String sql = "UPDATE brands SET brand_name=? WHERE brand_id=?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, newName);
                pst.setInt(2, id);
                pst.executeUpdate();

                loadBrands();
                JOptionPane.showMessageDialog(this, "Updated!");

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        JTextField txt = new JTextField();

        JPanel panel = new JPanel(new GridLayout(0,1));
        panel.add(new JLabel("Brand Name:"));
        panel.add(txt);

        int result = JOptionPane.showConfirmDialog(this, panel, "Add Brand", JOptionPane.OK_CANCEL_OPTION);

        if (result == JOptionPane.OK_OPTION) {
            String name = txt.getText().trim();

            if (name.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Empty field!");
                return;
            }

            try (Connection conn = MySQLConnect.getConnection()) {
                String sql = "INSERT INTO brands (brand_name) VALUES (?)";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, name);
                pst.executeUpdate();

                loadBrands();
                JOptionPane.showMessageDialog(this, "Added!");

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
