/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package irms.ui.frame;
import irms.auth.session;
import irms.ui.panel.adminHomePanel;
import irms.ui.panel.brandPanel;
import irms.ui.panel.cashierHomePanel;
import irms.ui.panel.categoryPanel;
import irms.ui.panel.customerPanel;
import irms.ui.panel.productsPanel;
import irms.ui.panel.reportsPanel;
import irms.ui.panel.salesPanel;
import irms.ui.panel.stockPanel;

import irms.ui.dialog.usersDialog;

/**
 *
 * @author USER
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        lblBackground.setIcon(new javax.swing.ImageIcon(
            getClass().getResource("/irms/resources/background/Home.png")
        ));
        actionbar.setIcon(new javax.swing.ImageIcon(
            getClass().getResource("/irms/resources/background/action bar.png")
        ));
        setLocationRelativeTo(null);
        applyRoleAccess();
        openHomePanel();
    }
    
        private void openHomePanel() {
        if (session.role != null && session.role.equalsIgnoreCase("ADMIN")) {
            showPanel(new adminHomePanel());
        } else {
            showPanel(new cashierHomePanel());
        }

        setActiveButton(btnHome);
    }
    
    private void applyRoleAccess() {
        if (session.role == null) {
            return;
        }

        if (session.role.equalsIgnoreCase("CASHIER")) {
            btnBrand.setVisible(false); 
            btnCategory.setVisible(false);   
            btnProducts.setVisible(false);   
            btnStocks.setVisible(false);     
            btnReports.setVisible(false);
            btnCustomers.setVisible(false);
            btnUser.setVisible(true);

        } else if (session.role.equalsIgnoreCase("ADMIN")) {
            btnBrand.setVisible(true);
            btnCategory.setVisible(true);
            btnProducts.setVisible(true);
            btnStocks.setVisible(true);
            btnReports.setVisible(true);
            btnCustomers.setVisible(true);
            btnUser.setVisible(true);
        }
    }
    
    public void showPanel(javax.swing.JPanel panel) {
        mainContentPanel.removeAll();
        mainContentPanel.setLayout(new java.awt.BorderLayout());
        mainContentPanel.add(panel, java.awt.BorderLayout.CENTER);
        mainContentPanel.revalidate();
        mainContentPanel.repaint();
        panel.revalidate();
        panel.repaint();
    }
    
    private void resetSidebarButtons() {
        java.awt.Color normalBg = new java.awt.Color(240, 240, 240);
        java.awt.Color normalFg = java.awt.Color.BLACK;

        btnHome.setBackground(normalBg);
        btnHome.setForeground(normalFg);

        btnSales.setBackground(normalBg);
        btnSales.setForeground(normalFg);

        btnCustomers.setBackground(normalBg);
        btnCustomers.setForeground(normalFg);

        btnBrand.setBackground(normalBg);
        btnBrand.setForeground(normalFg);

        btnCategory.setBackground(normalBg);
        btnCategory.setForeground(normalFg);

        btnProducts.setBackground(normalBg);
        btnProducts.setForeground(normalFg);

        btnStocks.setBackground(normalBg);
        btnStocks.setForeground(normalFg);

        btnReports.setBackground(normalBg);
        btnReports.setForeground(normalFg);
    }
    
    private void setActiveButton(javax.swing.JButton activeButton) {
        resetSidebarButtons();

        java.awt.Color activeBg = new java.awt.Color(126, 139, 74);
        java.awt.Color activeFg = java.awt.Color.WHITE;

        activeButton.setBackground(activeBg);
        activeButton.setForeground(activeFg);
    }
    
//    public void goHome() {
//        mainContentPanel.removeAll();
//        mainContentPanel.revalidate();
//        mainContentPanel.repaint();
//        setMainBackground("/irms/pages/home_bg.png");
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProducts = new javax.swing.JButton();
        btnSales = new javax.swing.JButton();
        btnStocks = new javax.swing.JButton();
        btnCategory = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnCustomers = new javax.swing.JButton();
        btnBrand = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        actionbar = new javax.swing.JLabel();
        mainContentPanel = new javax.swing.JPanel();
        pnlBackground = new javax.swing.JPanel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(200, 212, 222));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProducts.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irms/resources/icon/Products Module.png"))); // NOI18N
        btnProducts.setText(" PRODUCTS ");
        btnProducts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProducts.setFocusPainted(false);
        btnProducts.setPreferredSize(new java.awt.Dimension(94, 44));
        btnProducts.addActionListener(this::btnProductsActionPerformed);
        getContentPane().add(btnProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 190, -1));

        btnSales.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irms/resources/icon/Sales Module.png"))); // NOI18N
        btnSales.setText("    SALES       ");
        btnSales.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSales.setFocusPainted(false);
        btnSales.setPreferredSize(new java.awt.Dimension(94, 44));
        btnSales.addActionListener(this::btnSalesActionPerformed);
        getContentPane().add(btnSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 190, -1));

        btnStocks.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnStocks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irms/resources/icon/Stocks Module.png"))); // NOI18N
        btnStocks.setText("    STOCKS   ");
        btnStocks.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStocks.setFocusPainted(false);
        btnStocks.setPreferredSize(new java.awt.Dimension(94, 44));
        btnStocks.addActionListener(this::btnStocksActionPerformed);
        getContentPane().add(btnStocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 190, -1));

        btnCategory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irms/resources/icon/Category Module.png"))); // NOI18N
        btnCategory.setText(" CATEGORY ");
        btnCategory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCategory.setFocusPainted(false);
        btnCategory.setPreferredSize(new java.awt.Dimension(94, 44));
        btnCategory.addActionListener(this::btnCategoryActionPerformed);
        getContentPane().add(btnCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 190, -1));

        btnReports.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irms/resources/icon/Reports Module.png"))); // NOI18N
        btnReports.setText("   REPORTS  ");
        btnReports.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReports.setFocusPainted(false);
        btnReports.setPreferredSize(new java.awt.Dimension(94, 44));
        btnReports.addActionListener(this::btnReportsActionPerformed);
        getContentPane().add(btnReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 190, -1));

        btnCustomers.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCustomers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irms/resources/icon/Customers Module.png"))); // NOI18N
        btnCustomers.setText("CUSTOMERS");
        btnCustomers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCustomers.setFocusPainted(false);
        btnCustomers.setPreferredSize(new java.awt.Dimension(94, 44));
        btnCustomers.addActionListener(this::btnCustomersActionPerformed);
        getContentPane().add(btnCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 190, -1));

        btnBrand.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBrand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irms/resources/icon/Brands Module.png"))); // NOI18N
        btnBrand.setText("  BRAND     ");
        btnBrand.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBrand.setFocusPainted(false);
        btnBrand.setPreferredSize(new java.awt.Dimension(94, 44));
        btnBrand.addActionListener(this::btnBrandActionPerformed);
        getContentPane().add(btnBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 190, -1));

        btnUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irms/resources/icon/logo_icon.png"))); // NOI18N
        btnUser.setText("    USER       ");
        btnUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUser.setFocusPainted(false);
        btnUser.addActionListener(this::btnUserActionPerformed);
        getContentPane().add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 190, -1));

        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irms/resources/icon/Home Module.png"))); // NOI18N
        btnHome.setText("    HOME      ");
        btnHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHome.setFocusPainted(false);
        btnHome.setPreferredSize(new java.awt.Dimension(94, 44));
        btnHome.addActionListener(this::btnHomeActionPerformed);
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 190, -1));

        actionbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irms/resources/background/action bar.png"))); // NOI18N
        actionbar.setText("actionBar");
        getContentPane().add(actionbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, 770));

        mainContentPanel.setBackground(new java.awt.Color(200, 212, 222));
        mainContentPanel.setPreferredSize(new java.awt.Dimension(1130, 768));

        javax.swing.GroupLayout mainContentPanelLayout = new javax.swing.GroupLayout(mainContentPanel);
        mainContentPanel.setLayout(mainContentPanelLayout);
        mainContentPanelLayout.setHorizontalGroup(
            mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1130, Short.MAX_VALUE)
        );
        mainContentPanelLayout.setVerticalGroup(
            mainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        getContentPane().add(mainContentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, 800));

        pnlBackground.setBackground(new java.awt.Color(200, 212, 222));
        pnlBackground.setPreferredSize(new java.awt.Dimension(1366, 768));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irms/resources/background/Home.png"))); // NOI18N
        pnlBackground.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1110, 780));

        getContentPane().add(pnlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        usersDialog dialog = new usersDialog(this, true);
        dialog.setVisible(true);

    }//GEN-LAST:event_btnUserActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        openHomePanel();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesActionPerformed
        // TODO add your handling code here:
        showPanel(new salesPanel());
        setActiveButton(btnSales);

    }//GEN-LAST:event_btnSalesActionPerformed

    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
        // TODO add your handling code here:
        showPanel(new customerPanel());
        setActiveButton(btnCustomers);
    }//GEN-LAST:event_btnCustomersActionPerformed

    private void btnBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandActionPerformed
        // TODO add your handling code here:
        showPanel(new brandPanel());
        setActiveButton(btnBrand);
    }//GEN-LAST:event_btnBrandActionPerformed

    private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
        // TODO add your handling code here:
        showPanel(new categoryPanel());
        setActiveButton(btnCategory);
        
    }//GEN-LAST:event_btnCategoryActionPerformed

    private void btnProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsActionPerformed
        // TODO add your handling code here:
        showPanel(new productsPanel());
        setActiveButton(btnProducts);
        
    }//GEN-LAST:event_btnProductsActionPerformed

    private void btnStocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStocksActionPerformed
        // TODO add your handling code here:
        showPanel(new stockPanel());
        setActiveButton(btnStocks);
        
    }//GEN-LAST:event_btnStocksActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // TODO add your handling code here:
        showPanel(new reportsPanel());
        setActiveButton(btnReports);
    }//GEN-LAST:event_btnReportsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionbar;
    private javax.swing.JButton btnBrand;
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnProducts;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnSales;
    private javax.swing.JButton btnStocks;
    private javax.swing.JButton btnUser;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JPanel pnlBackground;
    // End of variables declaration//GEN-END:variables
}
